#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "sid_prototypes.h"
#include "random.h"
#include <xtimer.h>

/*
    This is an autogenerated function associated to 
    SID: 1007
    Module: data 
    Identifier: /sensor:sensorHealth
    function params: 
    Stable: false
*/
json_t* read_sensorHealth(json_t* coreconfInstance, SIDModelT* sidModel){
    json_t* traversedJSON;
    traversedJSON = traverseCORECONF(coreconfInstance, (uint64_t) SID_SENSORHEALTH);
	return traversedJSON;
}


/*
    This is an autogenerated function associated to 
    SID: 1008
    Module: data 
    Identifier: /sensor:sensorHealth/healthReadings
    function params: /sensor:sensorHealth/healthReadings/readingIndex
    Stable: false
*/
json_t* read_healthReadings(json_t* coreconfInstance, SIDModelT* sidModel, uint8_t readingIndex){


	// keys MUST be initialized properly and must be NON Empty
    int64_t keys[] = {readingIndex};
    size_t keyLength = sizeof(keys) / sizeof(keys[0]);

    IdentifierSIDT *sidIdentifier = malloc(sizeof(IdentifierSIDT));
    sidIdentifier->sid = SID_HEALTHREADINGS;
    sidIdentifier->identifier = "";
    // Initialize the leaf if it has a return type with a default value;
	json_t* queryTree = traverseCORECONFWithKeys(coreconfInstance, sidModel, sidIdentifier, keys, keyLength);

	
	if (queryTree != NULL){
		// Create a temporary sidString to query the tree
		char sidkeyString[21];
		snprintf(sidkeyString, 21, "%"PRId64, (uint64_t) SID_HEALTHVALUE);  
		uint32_t newHealthValue = read_healthValue(readingIndex);
		json_object_set(queryTree, sidkeyString, json_integer(newHealthValue));	
	}

	return queryTree;
}


/*
This function is NOT autogenerated
Return an arbitrary number based on the channel, similar to i2c/analog read functions
*/
int adc_sample(int channel){
    // Return an arbitrary number
    channel++;
	random_init(xtimer_now_usec()/1000);
	int randomValue =  random_uint32();;
    return randomValue;
} 


/*
    This is an autogenerated function associated to 
    SID: 1010
    Module: data 
    Identifier: /sensor:sensorHealth/healthReadings/healthValue
    function params: /sensor:sensorHealth/healthReadings/readingIndex
    Stable: false
*/
uint32_t read_healthValue(uint8_t readingIndex){
    // Initialize the leaf if it has a return type with a default value;
    uint32_t healthValueInstance  = 0;


    // Do something with the leaf
	switch (readingIndex){
        case 1:
            // If readingIndex is 1, get health value from channel 25
            healthValueInstance = (uint32_t) adc_sample(25);
            break;
        case 2:
            // If readingIndex is 2, get health value from channel 27
            healthValueInstance = (uint32_t) adc_sample(27);
            break;
        default:
            // Do nothing, healthValueInstance will be returned with its default value
            break;
	}
    // Return the leaf 
    return healthValueInstance;
}
        


/*
    This is an autogenerated function associated to 
    SID: 1012
    Module: data 
    Identifier: /sensor:sensordata
    function params: 
    Stable: false
*/
void read_sensordata(void){
}


/*
    This is an autogenerated function associated to 
    SID: 1013
    Module: data 
    Identifier: /sensor:sensordata/dataReadings
    function params: /sensor:sensordata/dataReadings/readingIndex
    Stable: false
*/
void read_dataReadings(uint8_t readingIndex){
    // Initialize the leaf if it has a return type with a default value;
    
    // Do something with the leaf
    readingIndex++;
}
        


/*
    This is an autogenerated function associated to 
    SID: 1014
    Module: data 
    Identifier: /sensor:sensordata/dataReadings/dataValue
    function params: /sensor:sensordata/dataReadings/readingIndex
    Stable: false
*/
uint16_t read_dataValue(uint8_t readingIndex){
    readingIndex++;
    // Initialize the leaf if it has a return type with a default value;
    uint16_t dataValueInstance  = 0;
	
    // Do something with the leaf
    // Return the leaf 
    return dataValueInstance;
}



        
// Function that returns a function pointer based on input value
// Manual mapping of SID to function call
json_t* readSwitch(int sid, json_t* coreconfInstance, SIDModelT* sidModel,int64_t keys[]) {
    json_t* responseJSON = json_object();
    char sidString[21];
    uint32_t healthValue;
    switch(sid){
        case SID_SENSORHEALTH:
            responseJSON = read_sensorHealth(coreconfInstance, sidModel);
            break;
        case SID_HEALTHREADINGS:
            // Should the keys[] be directly dereferenced?
            responseJSON = read_healthReadings(coreconfInstance, sidModel, keys[0]);
            break;
        case SID_HEALTHVALUE:
            healthValue = read_healthValue(keys[0]);
            // This returns a uint32_t, so format if before you add it
            snprintf(sidString, 21, "%d", sid);
            json_object_set(responseJSON, sidString, json_integer(healthValue));
            break;
        default:
            printf("Didn't understand SID %d",sid);
            break;
    }

    return responseJSON;

}

